### ISSUE TITLE
Personalized status commands

### ISSUE THREAD

**Issue by fannysoderlund** [homedork-se2/Mocked-client#12]
implementation of R4 - personalized status commands. Images for reference, but implementation is free. Applicable to both android and web. Connected to #13 

![image](https://user-images.githubusercontent.com/57757021/139038491-b7f8327a-8f2a-4b3f-82ae-d145f8107536.png)

![image](https://user-images.githubusercontent.com/57757021/139038582-5c4beb49-1897-47f5-b48a-4dcccf31794e.png)

![image](https://user-images.githubusercontent.com/57757021/139038606-2d18d358-08d7-4dcc-bd20-ada345c2c65b.png)

**Comment by szomer** [comment]
![webStatusCommands](https://user-images.githubusercontent.com/33659440/144658635-032d266b-2b56-4c65-b935-d9ee79bba6f2.PNG)

**Comment by fannysoderlund** [comment]
Done and to be implemented
