### ISSUE TITLE
High contrast

### ISSUE THREAD

**Issue by fannysoderlund** [homedork-se2/Mocked-client#9]
implementation of R3 - high contrast. Upon button click, the whole application should be in a high contrast mode that makes it easier for users to read. Applicable to both android and web.

**Comment by szomer** [comment]
![image](https://user-images.githubusercontent.com/33659440/142046590-52c1194b-6d0c-4358-b8d4-159cf3a2bcff.png)

**Comment by szomer** [comment]
![image](https://user-images.githubusercontent.com/33659440/142046787-b134692a-5cd9-49f8-ab1f-6b387533b32c.png)

**Comment by szomer** [comment]
![image](https://user-images.githubusercontent.com/33659440/142047024-51d23c3f-d3f5-4267-b099-105057101233.png)

**Comment by fannysoderlund** [comment]
Resolved by #24  and #27
